// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    feed,
    article,
    articleView,
    articleListView,
    articleFeedId,
    articleFts,
    articleAfterInsert,
    articleAfterDelete,
    articleAfterUpdate,
  ];
  late final Shape0 feed = Shape0(
    source: i0.VersionedTable(
      entityName: 'feed',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 article = Shape1(
    source: i0.VersionedTable(
      entityName: 'article',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_1,
        _column_5,
        _column_6,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 articleView = Shape2(
    source: i0.VersionedView(
      entityName: 'article_view',
      createViewStmt:
          'CREATE VIEW article_view AS SELECT a.*, f.icon, f.site_link FROM article AS a INNER JOIN feed AS f ON f.url = a.feed_id;',
      columns: [
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 articleListView = Shape3(
    source: i0.VersionedView(
      entityName: 'article_list_view',
      createViewStmt:
          'CREATE VIEW article_list_view AS SELECT a.id, a.feed_id, a.fetched, a.created, a.updated, a.last_read, a.title, a.authors, a.tags, a.links, a.summaryPlain, f.icon, f.site_link FROM article AS a INNER JOIN feed AS f ON f.url = a.feed_id;',
      columns: [
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_33,
        _column_37,
        _column_38,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index articleFeedId = i1.Index(
    'article_feed_id',
    'CREATE INDEX article_feed_id ON article (feed_id)',
  );
  late final Shape4 articleFts = Shape4(
    source: i0.VersionedVirtualTable(
      entityName: 'article_fts',
      moduleAndArgs:
          'fts5(title, summaryPlain, contentPlain, content=article, tokenize="trigram")',
      columns: [_column_1, _column_17, _column_20],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Trigger articleAfterInsert = i1.Trigger(
    'CREATE TRIGGER article_after_insert AFTER INSERT ON article BEGIN INSERT INTO article_fts ("rowid", title, summaryPlain, contentPlain) VALUES (new."rowid", new.title, new.summaryPlain, new.contentPlain);END',
    'article_after_insert',
  );
  final i1.Trigger articleAfterDelete = i1.Trigger(
    'CREATE TRIGGER article_after_delete AFTER DELETE ON article BEGIN INSERT INTO article_fts (article_fts, "rowid", title, summaryPlain, contentPlain) VALUES (\'delete\', old."rowid", old.title, old.summaryPlain, old.contentPlain);END',
    'article_after_delete',
  );
  final i1.Trigger articleAfterUpdate = i1.Trigger(
    'CREATE TRIGGER article_after_update AFTER UPDATE OF title, summaryPlain, contentPlain ON article WHEN OLD.title IS NOT NEW.title OR OLD.summaryPlain IS NOT NEW.summaryPlain OR OLD.contentPlain IS NOT NEW.contentPlain BEGIN INSERT INTO article_fts (article_fts, "rowid", title, summaryPlain, contentPlain) VALUES (\'delete\', old."rowid", old.title, old.summaryPlain, old.contentPlain);INSERT INTO article_fts ("rowid", title, summaryPlain, contentPlain) VALUES (new."rowid", new.title, new.summaryPlain, new.contentPlain);END',
    'article_after_update',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get icon =>
      columnsByName['icon']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get siteLink =>
      columnsByName['site_link']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authors =>
      columnsByName['authors']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tags =>
      columnsByName['tags']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastFetched =>
      columnsByName['last_fetched']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'PRIMARY KEY NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'icon',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'site_link',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'authors',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tags',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_fetched',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedId =>
      columnsByName['feed_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get fetched =>
      columnsByName['fetched']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updated =>
      columnsByName['updated']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastRead =>
      columnsByName['last_read']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authors =>
      columnsByName['authors']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tags =>
      columnsByName['tags']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get links =>
      columnsByName['links']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get summaryHtml =>
      columnsByName['summaryHtml']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get summaryMarkdown =>
      columnsByName['summaryMarkdown']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get summaryPlain =>
      columnsByName['summaryPlain']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentHtml =>
      columnsByName['contentHtml']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentMarkdown =>
      columnsByName['contentMarkdown']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentPlain =>
      columnsByName['contentPlain']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'PRIMARY KEY NOT NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES feed(url)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fetched',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_read',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'links',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'summaryHtml',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'summaryMarkdown',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'summaryPlain',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'contentHtml',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'contentMarkdown',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'contentPlain',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape2 extends i0.VersionedView {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedId =>
      columnsByName['feed_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get fetched =>
      columnsByName['fetched']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updated =>
      columnsByName['updated']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastRead =>
      columnsByName['last_read']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authors =>
      columnsByName['authors']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tags =>
      columnsByName['tags']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get links =>
      columnsByName['links']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get summaryHtml =>
      columnsByName['summaryHtml']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get summaryMarkdown =>
      columnsByName['summaryMarkdown']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get summaryPlain =>
      columnsByName['summaryPlain']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentHtml =>
      columnsByName['contentHtml']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentMarkdown =>
      columnsByName['contentMarkdown']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentPlain =>
      columnsByName['contentPlain']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get icon =>
      columnsByName['icon']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get siteLink =>
      columnsByName['site_link']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'feed_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fetched',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_read',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'authors',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tags',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'links',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'summaryHtml',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'summaryMarkdown',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'summaryPlain',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'contentHtml',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'contentMarkdown',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'contentPlain',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'icon',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'site_link',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

class Shape3 extends i0.VersionedView {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get feedId =>
      columnsByName['feed_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get fetched =>
      columnsByName['fetched']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get created =>
      columnsByName['created']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updated =>
      columnsByName['updated']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastRead =>
      columnsByName['last_read']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authors =>
      columnsByName['authors']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tags =>
      columnsByName['tags']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get links =>
      columnsByName['links']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get summaryPlain =>
      columnsByName['summaryPlain']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get icon =>
      columnsByName['icon']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get siteLink =>
      columnsByName['site_link']! as i1.GeneratedColumn<String>;
}

class Shape4 extends i0.VersionedVirtualTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get summaryPlain =>
      columnsByName['summaryPlain']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentPlain =>
      columnsByName['contentPlain']! as i1.GeneratedColumn<String>;
}

i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
